apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: arc-github-app-secret      # K8s secret name ARC expects
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: arc/github-app-secret
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: arc/github-app-secret
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: arc/github-app-secret
        property: github_app_private_key
